language: python

python:
  - "3.6"

services:
  - xvfb

before_script:
  # From the travis docs: https://docs.travis-ci.com/user/gui-and-headless-browsers/
  # To run tests requiring a graphical user interface on Travis CI, use xvfb (X Virtual Framebuffer)
  # Also see: https://stackoverflow.com/questions/55674746/travis-sh-0-cant-open-etc-init-d-xvfb
  - export DISPLAY=:99.0
  - export QT_DEBUG_PLUGINS=1

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  
  - pip install -U pip
  - python setup.py install              # install your package
  - pip install -r requirements-dev.txt  # install requirements
  - pip install coveralls
  
script:
  - python -m pytest
  - coverage run -m pytest

after_success:
  - coveralls
